### ISSUE TITLE
Tests fail with newer http-parser library (2.1 was okay, 2.7.1 is failing)

### ISSUE THREAD

**Issue by cbiedl** [igrigorik/em-http-request#316]
Hello,

as reported in the Debian BTS <https://bugs.debian.org/881627>, em-http-request started to fail the test suite after http-parser was upgraded from 2.1 to 2.7.1, the problem still exists with the most recent version 2.8.1.

The most important error lines are:
```
     NoMethodError:
       undefined method `continue?' for nil:NilClass
     # ./lib/em-http/http_connection.rb:134:in `block in post_init'
```

After staring at the code for a long time and using Ruby's "Tracer" it seems http-parser calls message_complete more often than in earlier times but your library cannot deal with this. I might be completely wrong here, especially since I couldn't find any releated change in http-parser. Before starting a fairly annoying `git bisect` session, I'm asking you to take a look - my Ruby knowledge is basically "guessing from looking at the code".

**Comment by cbiedl** [comment]
Two more things: The Debian bug mentioned above now also has a small patch. It mitigates the issue by working around the still unknown underlying issue.

And second, AFAICT this is about testing http-parser's behavior in an uncommon or "this should not happen" situation. Could you please get in touch with upstream at https://github.com/nodejs/http-parser to have this test embedded there? Beside defining the behavior, this would allow bindings to benefit from this clarification.

**Comment by igrigorik** [comment]
Hmm, I'm a little confused.. The discussion in https://bugs.debian.org/881627 seems to be about header parsing, which is upstream and independent Ruby http-parser.rb — /cc @bnoordhuis @indutny fyi. If there is a bug in Node's test suite or implementation, we should open an issue there.

Can you elaborate more on what's causing the em-http-request error you're seeing above?

**Comment by bnoordhuis** [comment]
I can take a look if you have a pure http-parser test case, no ruby, and it reproduces with the latest release, v2.8.1.

**Comment by boutil** [comment]
Hi,

For the record, I think that the bug report @cbiedl wanted to point out is: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882308 (not 881627).

**Comment by igrigorik** [comment]
Closing, please reopen if there is still an em-http issue here.
