### PR TITLE
Fix failing specs and replace TravisCI with GitHub Actions

### PR DESCRIPTION
**Pull request by mattbrictson**
Three specs were failing on the `master` branch. This PR fixes all three specs.

Furthermore, this repo currently had no CI coverage because Travis builds were no longer running. To fix this, this PR removes the Travis config and switches to a GitHub Actions workflow for CI.

The Travis config only tested Ruby 2.2; the new GitHub Actions workflow tests Ruby 2.2 through 3.2.

### CODE REVIEW

File: lib/em-http/http_connection.rb [hunk 1]
```diff
@@ -198,7 +198,7 @@ def post_init
       end
 
       @p.on_message_complete = proc do
-        if !client.continue?
+        if client && !client.continue?
```
Comment (mattbrictson) [inline lib/em-http/http_connection.rb:201]: 🗒️ This code was introduced in 3a9b96c2f31f29c112a11b934fee7d40cafd4dcc but the corresponding spec never worked. It failed with this error:

```
NoMethodError:
  undefined method `continue?' for nil:NilClass
```

This change fixes the nil error so that the spec passes as intended.

File: spec/external_spec.rb [hunk 2]
```diff
@@ -80,11 +80,10 @@
     end
 
     it "should detect deflate encoding" do
-      # pending "need an endpoint which supports deflate.. MSN is no longer"
       EventMachine.run {
 
         options = {:head => {"accept-encoding" => "deflate"}, :redirects => 5}
-        http = EventMachine::HttpRequest.new('http://www.libpng.org/').get options
+        http = EventMachine::HttpRequest.new('https://www.bing.com/').get options
```
Comment (mattbrictson) [inline spec/external_spec.rb:86]: 🗒️ libpng.org no longer supports deflate, but bing.com does.

File: spec/ssl_spec.rb [hunk 3]
```diff
@@ -9,7 +9,7 @@
 
         http.errback { failed(http) }
         http.callback {
-          http.response_header.status.should == 302
+          http.response_header.status.should == 301
```
Comment (mattbrictson) [inline spec/ssl_spec.rb:12]: 🗒️ The Gmail URL being tested by this spec now returns a different status.

File: lib/em-http/http_connection.rb [hunk 4]
```diff
@@ -190,6 +190,7 @@ def post_init
           # the connection because we're processing invalid HTTP
           @p.reset!
           unbind
+          :stop
```
Comment (mattbrictson) [inline lib/em-http/http_connection.rb:193]: 🗒️ This code was introduced in 3a9b96c2f31f29c112a11b934fee7d40cafd4dcc but the corresponding spec never worked. It failed with this error:

```
NoMethodError:
  undefined method `continue?' for nil:NilClass
```

This change fixes the failing spec as proposed by @jackorp in #356.

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+        ruby:
+          [
+            "2.3",
+            "2.4",
+            "2.5",
+            "2.6",
+            "2.7",
+            "3.0",
+            "3.1",
+            "3.2"
```
Comment (MatheusRich) [inline .github/workflows/ci.yml:22]:
```suggestion
            "3.2",
            "3.3"
```

**Comment by MatheusRich** [comment]
@igrigorik Can you take a look at this PR? I think this gem has a Ruby 3.3 incompatibility, so I'd love to see it added to the CI testing pipeline.

**Review by igrigorik — APPROVED** [review]
👍 thanks for the cleanup & fixes.

**Comment by mattbrictson** [comment]
@igrigorik apologies, it looks like there was a typo in my workflow file that is causing the action to fail. I'll open a follow-up PR to fix it.
